version: 2
updates:
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "daily"
  versioning-strategy: increase
  groups: # start with everything in one PR ...
    python-packages:
      patterns:
        - "*"