# This file is for reference only, it is not imported into the pyproject toml. Settings are copy-pasted there ...

lint.extend-ignore = [
    "D401", # First line of docstring should be in imperative mood ("Returns ..." is OK, for example)
    "D203", # 1 blank line required before class docstring (No thank you, only after the class docstring)
    "D212", # Multi-line docstring summary should start at the first line (We start on new line, D209)
    "D215", # Section underline is over-indented (No underlines)
    "D400", # First line should end with a period (We allow any punctuation, D415)
    "D406", # Section name should end with a newline (We use a colon, D416)
    "D407", # Missing dashed underline after section (No underlines)
    "D408", # Section underline should be in the line following the section's name (No underlines)
    "D409", # Section underline should match the length of its name (No underlines)
    "D413", # Missing blank line after last section (Not required)
]

# Explicit is better than implicit
lint.extend-select = [
    "D100", # Missing docstring in public module
    "D101", # Missing docstring in public class
    "D102", # Missing docstring in public method
    "D103", # Missing docstring in public function
    "D104", # Missing docstring in public package
    "D105", # Missing docstring in magic method
    "D106", # Missing docstring in public nested class
    "D107", # Missing docstring in __init__
    "D200", # One-line docstring should fit on one line
    "D201", # No blank lines allowed before function docstring (found {num_lines})
    "D202", # No blank lines allowed after function docstring (found {num_lines})
    "D204", # 1 blank line required after class docstring
    "D205", # 1 blank line required between summary line and description
    "D206", # Docstring should be indented with spaces, not tabs
    "D207", # Docstring is under-indented
    "D208", # Docstring is over-indented
    "D209", # Multi-line docstring closing quotes should be on a separate line
    "D210", # No whitespaces allowed surrounding docstring text
    "D211", # No blank lines allowed before class docstring
    "D213", # Multi-line docstring summary should start at the second line
    "D214", # Section is over-indented ("{name}")
    "D300", # Use triple double quotes """
    "D301", # Use r""" if any backslashes in a docstring
    "D402", # First line should not be the function's signature
    "D403", # irst word of the first line should be capitalized: {} -> {}
    "D404", # First word of the docstring should not be "This"
    "D405", # Section name should be properly capitalized ("{name}")
    "D410", # Missing blank line after section ("{name}")
    "D411", # Missing blank line before section ("{name}")
    "D412", # No blank lines allowed between a section header and its content ("{name}")
    "D414", # Section has no content ("{name}")
    "D415", # First line should end with a period, question mark, or exclamation point
    "D416", # Section name should end with a colon ("{name}")
    "D417", # Missing argument description in the docstring for {definition}: {name}
    "D418", # Function decorated with @overload shouldn't contain a docstring
    "D419", # Docstring is empty
]