site_name: "recurtools"
repo_url: https://github.com/MusicalNinjaDad/recurtools
repo_name: MusicalNinjaDad/recurtools

watch:
- recurtools # To update live preview when docstrings change

theme:
  name: "material"

plugins:
- search
- mkdocstrings

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences