site_name: "recurtools"
repo_url: https://github.com/MusicalNinjaDad/recurtools
repo_name: MusicalNinjaDad/recurtools

watch:
- recurtools # To update live preview when docstrings change

theme:
  name: "material"
  icon:
    logo: fontawesome/solid/diagram-next
  palette: # Palette toggles for auto-light-dark mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to system preference
  features:
    - navigation.expand
    - navigation.path
    - navigation.indexes

plugins:
- search
- mkdocstrings

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home:
    - index.md
