site_name: "recurtools"
repo_url: https://github.com/MusicalNinjaDad/recurtools
repo_name: MusicalNinjaDad/recurtools

theme:
  name: "material"

plugins:
- search
- mkdocstrings

watch:
- recurtools # To update live preview when docstrings change