name: Publish to PyPi

on: # push the __version__ file to main to trigger publishing
    push:
        branches:
            - 'main'
        paths:
            - '__version__'

jobs:
    build:
        name: Build package
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.x"
            - name: Install build
              run: python -m pip install build --user
            - name: Build
              run: python -m build
            - name: Store distribution packages
              uses: actions/upload-artifact@v3
              with:
                name: python-package-distributions
                path: dist/

    publish:
        name: Publish to PyPi
        needs:
            - build
        runs-on: ubuntu-latest
        environment:
            name: pypi
            url: https://pypi.org/p/recurtools
        permissions:
            id-token: write
        steps:
            - name: Retrieve distribution packages
              uses: actions/download-artifact@v3
              with:
                name: python-package-distributions
                path: dist/
            - name: Upload to PyPi
              uses: pypa/gh-action-pypi-publish@release/v1